// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://alpdddwpjrwapqedcwdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFscGRkZHdwanJ3YXBxZWRjd2R3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNDIwOTMsImV4cCI6MjA3MzYxODA5M30.JUT-3XeEpmprpGJnkndF0F7T8WaIt_y_Dslof2meeTA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});